# Generated by Django 4.1.2 on 2022-11-04 14:44

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=djrichtextfield.models.RichTextField(verbose_name='Contenido'),
        ),
    ]
